name: Tests

on:
  pull_request:
    types: [opened, edited, synchronize, commit]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      POSTGRES_USER: test_pg_user
      POSTGRES_PASSWORD: 123456
      DATABASE_USER: test_user
      DATABASE_PASSWORD: 123456
      DATABASE_NAME: test_database
      DATABASE_URL: "postgres://test_pg_user:123456@127.0.0.1:5432/test_database"
      REDIS_HOST: "127.0.0.1"
      REDIS_PORT: "6379"
      CLICKHOUSE_HOST: "127.0.0.1"
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_USER: ""
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_SCHEMA: "default"
      CLICKHOUSE_PROTOCOL: "http"

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: POSTGRES_USER
          POSTGRES_PASSWORD: POSTGRES_PASSWORD
          POSTGRES_DB: DATABASE_NAME
        ports:
          - 127.0.0.1:5432:5432
      redis:
        image: redis:latest
        ports:
          - 127.0.0.1:6379:6379

      clickhouse:
        image: clickhouse/clickhouse-server:23.8.2.7-alpine
        ports:
          - 127.0.0.1:8123:8123

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.2

      - name: Checkout code
        uses: actions/checkout@v2

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd src && python -m pytest